import * as React from "react";
import type { ChatMessageContract, ConversationContract } from "@nhuu-chat/contracts";
import { MessageComposer } from "./MessageComposer.js";
import { InboxIcon } from "./InboxIcon.js";
import { conversationDisplayName, conversationInitials, formatConversationTime } from "../../state/inbox-ui.js";
export function ChatWindow({ conversation, messages, onSend }: { conversation: ConversationContract | null; messages: ChatMessageContract[]; onSend: (content: string) => Promise<void> }) {
  if (!conversation) return <section className="chat-main flex min-w-0 min-h-0 flex-col bg-slate-100 max-[680px]:hidden" aria-label="Cửa sổ chat"><div className="chat-empty-state grid h-full place-content-center justify-items-center p-6 text-center"><div className="chat-empty-icon grid size-[120px] place-items-center rounded-full bg-white text-blue-600 shadow-sm"><InboxIcon name="chat" size={52} /></div><h1 className="mt-7 text-[29px] font-semibold text-gray-800">Chào mừng bạn đến với Livechat</h1><p className="mt-3.5 text-base text-gray-500">Chọn một hội thoại từ danh sách bên trái để bắt đầu.</p></div></section>;
  const name = conversationDisplayName(conversation);
  return <section className="chat-main flex min-w-0 min-h-0 flex-col bg-slate-100 max-[680px]:hidden" aria-label="Cửa sổ chat"><header className="chat-header flex min-h-[72px] items-center gap-3 border-b border-gray-200 bg-white px-6 py-3.5"><span className="conversation-avatar grid size-[42px] shrink-0 place-items-center rounded-full bg-blue-100 text-[13px] font-bold text-blue-700">{conversationInitials(name)}</span><div><h2 className="mb-1 text-base font-semibold">{name}</h2><small className="text-xs text-gray-500">{conversation.platform === "telegram_personal" ? "Telegram" : conversation.platform} · Đang hoạt động</small></div><button className="chat-header-action ml-auto grid place-items-center text-gray-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-300" type="button" aria-label="Thông tin hội thoại"><InboxIcon name="users" /></button></header><div className="chat-messages min-h-0 flex-1 overflow-y-auto p-6">{messages.length === 0 ? <p className="chat-no-messages text-center text-gray-400">Chưa có tin nhắn</p> : messages.map((message) => <article className={`chat-message my-2 flex ${message.senderType === "customer" ? "justify-start" : "justify-end"}`} key={message.id}><div className={`chat-message-bubble max-w-[min(560px,75%)] rounded-lg px-3 py-2.5 ${message.senderType === "customer" ? "bg-white" : "bg-blue-100"}`}><p className="m-0 text-sm leading-[1.45]">{message.content}</p><time className="mt-1 block text-[11px] text-gray-400">{formatConversationTime(message.createdAt)}</time></div></article>)}</div><MessageComposer onSend={onSend} /></section>;
}
