import * as React from "react";
import { useEffect, useState } from "react";
import type { ConversationNoteContract } from "@nhuu-chat/contracts";
import { apiRequest } from "../../lib/api.js";
import { InboxIcon } from "./InboxIcon.js";
import { ConversationAvatar } from "./ConversationAvatar.js";

type SidebarTab = "info" | "create-order";
type NoteAction = (note: ConversationNoteContract) => Promise<void>;

function NoteCard({ note, onEdit, onDelete, onTogglePin }: { note: ConversationNoteContract; onEdit: NoteAction; onDelete: NoteAction; onTogglePin: NoteAction }) {
  const [editing, setEditing] = useState(false);
  const [content, setContent] = useState(note.content);
  const [busy, setBusy] = useState(false);
  async function saveEdit() { if (!content.trim() || busy) return; setBusy(true); try { await onEdit({ ...note, content: content.trim() }); setEditing(false); } finally { setBusy(false); } }
  async function run(action: NoteAction) { if (busy) return; setBusy(true); try { await action(note); } finally { setBusy(false); } }
  return <article className={`group min-w-0 rounded-lg border bg-white p-3 shadow-sm ${note.isPinned ? "border-blue-200" : "border-gray-200"}`}>
    <div className="flex items-start gap-2"><ConversationAvatar name={note.authorName} avatarUrl={note.authorAvatarUrl} size="size-8" /><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-gray-800">{note.authorName}</p><time className="block whitespace-nowrap text-[10px] text-gray-400">{new Date(note.updatedAt).toLocaleString("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" })}</time></div><div className="flex w-1/5 min-w-[60px] max-w-[72px] shrink-0 items-center justify-end gap-0 text-gray-400"><button className="invisible grid size-5 place-items-center rounded-md hover:bg-gray-100 hover:text-blue-600 disabled:opacity-50 group-hover:visible group-focus-within:visible" type="button" onClick={() => setEditing(true)} disabled={busy} aria-label="Sửa ghi chú"><InboxIcon name="edit" size={12} /></button><button className="invisible grid size-5 place-items-center rounded-md hover:bg-gray-100 hover:text-red-600 disabled:opacity-50 group-hover:visible group-focus-within:visible" type="button" onClick={() => void run(onDelete)} disabled={busy} aria-label="Xóa ghi chú"><InboxIcon name="trash" size={12} /></button><button className={`grid size-5 place-items-center rounded-md hover:bg-gray-100 hover:text-blue-600 disabled:opacity-50 group-hover:visible group-focus-within:visible ${note.isPinned ? "visible text-yellow-500" : "invisible"}`} type="button" onClick={() => void run(onTogglePin)} disabled={busy} aria-label="Ghim ghi chú"><InboxIcon name="pin" size={12} /></button></div></div>
    {editing ? <div className="mt-2 grid gap-2"><textarea className="min-h-16 w-full resize-y rounded-md border border-gray-200 px-2 py-1.5 text-xs text-gray-800 outline-none focus:border-blue-300 focus:ring-2 focus:ring-blue-600/10" value={content} onChange={(event) => setContent(event.target.value)} aria-label="Nội dung ghi chú đang sửa" autoFocus /><div className="flex justify-end gap-2"><button className="rounded-md px-2 py-1 text-[11px] font-semibold text-gray-500 hover:bg-gray-100" type="button" onClick={() => { setContent(note.content); setEditing(false); }}>Hủy</button><button className="rounded-md bg-blue-600 px-2 py-1 text-[11px] font-semibold text-white disabled:opacity-50" type="button" onClick={() => void saveEdit()} disabled={busy || !content.trim()}>Lưu</button></div></div> : <><p className="mt-2 whitespace-pre-wrap break-words text-xs leading-5 text-gray-700">{note.content}</p>{note.updatedAt !== note.createdAt && <span className="mt-1 block text-[10px] font-medium text-blue-600">• Đã sửa</span>}</>}
  </article>;
}

function NoteBlock({ notes, onCreate, onEdit, onDelete, onTogglePin }: { notes: ConversationNoteContract[]; onCreate: (content: string) => Promise<void>; onEdit: NoteAction; onDelete: NoteAction; onTogglePin: NoteAction }) {
  const [content, setContent] = useState("");
  const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!content.trim() || busy) return; setBusy(true); try { await onCreate(content.trim()); setContent(""); } finally { setBusy(false); } }
  return <section className="rounded-xl bg-gray-50 p-3" aria-labelledby="conversation-note-title"><h3 className="mb-3 text-sm font-bold text-gray-800" id="conversation-note-title">Ghi chú</h3>{notes.length === 0 ? <div className="grid justify-items-center rounded-lg px-2 py-4 text-center text-gray-400"><InboxIcon name="note" size={34} /><p className="mt-2 text-xs font-medium">Bạn chưa có ghi chú nào</p></div> : <div className="grid min-w-0 gap-2">{notes.map((note) => <NoteCard key={note.id} note={note} onEdit={onEdit} onDelete={onDelete} onTogglePin={onTogglePin} />)}</div>}<form className="mt-3" onSubmit={submit}><input className="w-full rounded-lg border border-gray-200 bg-white px-3 py-2 text-xs text-gray-800 outline-none placeholder:text-gray-400 focus:border-blue-300 focus:ring-4 focus:ring-blue-600/10 disabled:bg-gray-100" aria-label="Ghi chú hội thoại" placeholder="Nhập ghi chú (Enter để gửi)" value={content} onChange={(event) => setContent(event.target.value)} disabled={busy} /></form></section>;
}

function OrderBlock() { return <section className="mt-5" aria-labelledby="conversation-order-title"><h3 className="mb-3 text-sm font-bold text-gray-800" id="conversation-order-title">Đơn hàng</h3><div className="grid justify-items-center rounded-xl border-2 border-dashed border-gray-200 px-3 py-6 text-center text-gray-400"><div className="relative grid size-12 place-items-center rounded-full bg-gray-100"><InboxIcon name="list" size={26} /><span className="absolute -right-1 -top-1 grid size-5 place-items-center rounded-full bg-white text-[10px] font-bold text-gray-400 shadow-sm">0</span></div><p className="mt-3 text-xs">Chưa có lịch sử đơn hàng</p><button className="mt-4 inline-flex items-center gap-1 rounded-lg border border-gray-200 bg-white px-3 py-2 text-xs font-semibold text-gray-700 shadow-sm" type="button"><InboxIcon name="plus" size={14} /> + Tạo đơn</button></div></section>; }
function CreateOrderPanel() { return <section className="rounded-xl border border-gray-200 bg-gray-50 p-4" aria-labelledby="create-order-title"><h3 className="text-sm font-bold text-gray-800" id="create-order-title">Tạo đơn</h3><p className="mt-3 text-xs leading-5 text-gray-500">Bắt đầu tạo đơn hàng từ hội thoại này.</p><button className="mt-4 inline-flex w-full items-center justify-center gap-1 rounded-lg bg-blue-600 px-3 py-2 text-xs font-semibold text-white" type="button"><InboxIcon name="plus" size={14} /> + Tạo đơn</button></section>; }

function SidebarContent({ activeTab, setActiveTab, hasConversation, notes, onCreate, onEdit, onDelete, onTogglePin }: { activeTab: SidebarTab; setActiveTab: (tab: SidebarTab) => void; hasConversation: boolean; notes: ConversationNoteContract[]; onCreate: (content: string) => Promise<void>; onEdit: NoteAction; onDelete: NoteAction; onTogglePin: NoteAction }) {
  if (!hasConversation) return <div className="grid min-h-0 flex-1 place-items-center p-6 text-center text-sm text-gray-400">Chưa có thông tin khách hàng</div>;
  return <><nav className="flex shrink-0 border-b border-gray-200 px-4" aria-label="Khu vực thông tin bổ trợ"><button className={`border-b-2 px-3 py-3 text-xs font-semibold ${activeTab === "info" ? "border-blue-600 text-blue-600" : "border-transparent text-gray-500"}`} type="button" onClick={() => setActiveTab("info")} aria-selected={activeTab === "info"}>Thông tin</button><button className={`border-b-2 px-3 py-3 text-xs font-semibold ${activeTab === "create-order" ? "border-blue-600 text-blue-600" : "border-transparent text-gray-500"}`} type="button" onClick={() => setActiveTab("create-order")} aria-selected={activeTab === "create-order"}>Tạo đơn</button></nav><div className="min-h-0 flex-1 overflow-y-auto scrollbar-none p-4">{activeTab === "info" ? <><NoteBlock notes={notes} onCreate={onCreate} onEdit={onEdit} onDelete={onDelete} onTogglePin={onTogglePin} /><OrderBlock /></> : <CreateOrderPanel />}</div></>;
}

function SidebarPanel({ mobile = false, onClose, ...props }: { mobile?: boolean; onClose?: () => void; hasConversation: boolean; activeTab: SidebarTab; setActiveTab: (tab: SidebarTab) => void; notes: ConversationNoteContract[]; onCreate: (content: string) => Promise<void>; onEdit: NoteAction; onDelete: NoteAction; onTogglePin: NoteAction }) { return <aside className={mobile ? "fixed inset-y-0 right-0 z-50 flex w-[min(340px,calc(100vw-44px))] flex-col border-l border-gray-200 bg-white shadow-2xl" : "hidden min-h-0 w-[300px] shrink-0 flex-col border-l border-gray-200 bg-white min-[1000px]:flex"} aria-label="Thông tin bổ trợ cuộc hội thoại">{mobile && <div className="flex items-center justify-between border-b border-gray-100 px-4 py-3"><span className="text-sm font-bold text-gray-800">Thông tin hội thoại</span><button className="grid size-8 place-items-center rounded-md text-gray-500 hover:bg-gray-100" type="button" onClick={onClose} aria-label="Đóng thông tin hội thoại"><InboxIcon name="close" size={17} /></button></div>}<SidebarContent {...props} /></aside>; }

export function ConversationInfoSidebar({ mobileOpen = false, onClose, hasConversation = true, conversationId, token = "", refresh }: { mobileOpen?: boolean; onClose?: () => void; hasConversation?: boolean; conversationId?: string | null; token?: string; refresh?: () => Promise<string | null> }) {
  const context = (globalThis as typeof globalThis & { __nhuuChatConversationContext?: { id: string | null; token: string; refresh?: () => Promise<string | null> } }).__nhuuChatConversationContext;
  conversationId ??= context?.id;
  token = token || context?.token || "";
  refresh ??= context?.refresh;
  const [activeTab, setActiveTab] = useState<SidebarTab>("info");
  const [notes, setNotes] = useState<ConversationNoteContract[]>([]);
  // Chỉ áp dụng phản hồi notes của hội thoại hiện tại, tránh request cũ ghi đè khi đổi chat nhanh.
  useEffect(() => { if (!conversationId || !hasConversation) { setNotes([]); return; } let cancelled = false; void apiRequest<{ notes: ConversationNoteContract[] }>("", `/api/v1/conversations/${conversationId}/notes`, token, {}, refresh).then((result) => { if (!cancelled) setNotes(result.notes); }).catch(() => { if (!cancelled) setNotes([]); }); return () => { cancelled = true; }; }, [conversationId, hasConversation, token, refresh]);
  async function createNote(content: string) { if (!conversationId) return; const note = await apiRequest<ConversationNoteContract>("", `/api/v1/conversations/${conversationId}/notes`, token, { method: "POST", body: JSON.stringify({ content }) }, refresh); setNotes((current) => [note, ...current]); }
  async function editNote(note: ConversationNoteContract) { if (!conversationId) return; const updated = await apiRequest<ConversationNoteContract>("", `/api/v1/conversations/${conversationId}/notes/${note.id}`, token, { method: "PATCH", body: JSON.stringify({ content: note.content }) }, refresh); setNotes((current) => current.map((item) => item.id === updated.id ? updated : item)); }
  async function deleteNote(note: ConversationNoteContract) { if (!conversationId || !window.confirm("Xóa ghi chú này?")) return; await apiRequest<void>("", `/api/v1/conversations/${conversationId}/notes/${note.id}`, token, { method: "DELETE" }, refresh); setNotes((current) => current.filter((item) => item.id !== note.id)); }
  async function togglePin(note: ConversationNoteContract) { if (!conversationId) return; const updated = await apiRequest<ConversationNoteContract>("", `/api/v1/conversations/${conversationId}/notes/${note.id}/pin`, token, { method: "PATCH", body: JSON.stringify({ isPinned: !note.isPinned }) }, refresh); setNotes((current) => current.map((item) => item.id === updated.id ? updated : item).sort((a, b) => Number(b.isPinned) - Number(a.isPinned) || Date.parse(b.updatedAt) - Date.parse(a.updatedAt))); }
  const panelProps = { hasConversation, activeTab, setActiveTab, notes, onCreate: createNote, onEdit: editNote, onDelete: deleteNote, onTogglePin: togglePin };
  return <><SidebarPanel {...panelProps} />{mobileOpen && <><button className="fixed inset-0 z-40 bg-slate-900/30 min-[1000px]:hidden" type="button" onClick={onClose} aria-label="Đóng bảng thông tin" /><SidebarPanel {...panelProps} mobile onClose={onClose} /></>}</>;
}
