import * as React from "react";
import { useMemo, useState } from "react";
import type { ConversationContract } from "@nhuu-chat/contracts";
import { conversationDisplayName, conversationInitials, formatConversationTime } from "../../state/inbox-ui.js";
import { InboxIcon } from "./InboxIcon.js";
export function ConversationList({ items, activeId, onSelect }: { items: ConversationContract[]; activeId: string | null; onSelect: (id: string) => void }) {
  const [search, setSearch] = useState("");
  const filtered = useMemo(() => items.filter((item) => `${item.channelId} ${item.lastMessageSnippet}`.toLowerCase().includes(search.toLowerCase())), [items, search]);
  return <aside className="conversation-sidebar flex min-w-0 flex-col overflow-hidden border-r border-gray-200 bg-white" aria-label="Danh sách hội thoại">
    <div className="conversation-toolbar grid grid-cols-[minmax(0,1fr)_82px_40px] gap-2 p-3 max-[680px]:grid-cols-[minmax(0,1fr)_40px]"><label className="conversation-search flex h-10 min-w-0 items-center gap-2 rounded-lg border border-gray-200 px-2.5 text-gray-400 transition-shadow focus-within:border-blue-300 focus-within:ring-4 focus-within:ring-blue-600/10"><InboxIcon name="search" size={17} /><input className="w-full min-w-0 border-0 bg-transparent text-sm text-gray-800 outline-none placeholder:text-gray-400" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Tìm tên, sđt..." aria-label="Tìm hội thoại" /></label><button className="conversation-filter flex h-10 items-center justify-around rounded-lg border border-gray-200 bg-white text-[13px] text-gray-600 hover:bg-slate-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-300 max-[680px]:hidden" type="button"><span>Tất cả</span><span>⌄</span></button><button className="conversation-add grid h-10 place-items-center rounded-lg border border-gray-200 bg-white text-gray-600 hover:bg-slate-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-300" type="button" aria-label="Thêm hội thoại"><InboxIcon name="plus" /></button></div>
    <div className="conversation-list-header flex min-h-11 items-center justify-between border-y border-gray-200 px-3 text-sm font-semibold text-gray-600"><span>Tất cả hội thoại <b className="ml-1 rounded-full bg-gray-100 px-1.5 py-0.5 text-[11px] text-gray-500">{items.length}</b></span><button className="grid place-items-center text-gray-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-300" type="button" aria-label="Tùy chọn danh sách"><InboxIcon name="list" /></button></div>
    <div className="conversation-items min-h-0 overflow-y-auto">{filtered.length === 0 ? <div className="conversation-list-empty px-4 py-10 text-center text-[13px] text-gray-400">Chưa có hội thoại</div> : filtered.map((item) => { const name = conversationDisplayName(item); return <button className={`conversation-item relative flex min-h-[74px] w-full items-start gap-2.5 border-0 border-b border-gray-100 px-3 py-3.5 text-left text-gray-800 transition-colors hover:bg-slate-50 focus-visible:z-10 focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-blue-300 ${item.id === activeId ? "bg-blue-50" : "bg-white"}`} key={item.id} onClick={() => onSelect(item.id)} aria-current={item.id === activeId}><span className="conversation-avatar grid size-[42px] shrink-0 place-items-center rounded-full bg-blue-100 text-[13px] font-bold text-blue-700">{conversationInitials(name)}</span><span className="conversation-item-content grid min-w-0 flex-1 gap-1"><span className="conversation-item-top flex min-w-0 items-center justify-between gap-2"><strong className="truncate text-sm font-semibold">{name}</strong><time className="shrink-0 text-xs text-gray-400">{formatConversationTime(item.lastMessageAt)}</time></span><span className="conversation-preview truncate text-xs text-gray-500">{item.lastMessageSnippet || "Hội thoại mới"}</span><span className="conversation-sender flex items-center gap-1 truncate text-xs text-gray-400"><InboxIcon name="chat" size={13} /> {item.platform === "telegram_personal" ? "Telegram" : item.platform}</span></span>{item.unreadCount > 0 && <span className="conversation-unread grid size-5 shrink-0 place-items-center rounded-full bg-red-500 text-[11px] font-bold text-white">{item.unreadCount}</span>}</button>; })}</div>
  </aside>;
}
