import * as React from "react";
import { motion, useReducedMotion } from "framer-motion";
import type { AuthRole } from "../../state/auth.store.js";

export interface LandingPageProps {
  user: { email: string; role: AuthRole } | null;
  onDashboard: () => void;
  onLogin: () => void;
  onRegister: () => void;
}

type IconName = "arrow" | "bot" | "chart" | "check" | "chevron" | "facebook" | "globe" | "instagram" | "layers" | "mail" | "message" | "monitor" | "send" | "shield" | "shop" | "sparkle" | "telegram" | "tiktok" | "users" | "website" | "workflow" | "zalo";

const iconPaths: Record<IconName, React.ReactNode> = {
  arrow: <path d="M5 12h14m-6-6 6 6-6 6" />, bot: <><rect x="5" y="7" width="14" height="12" rx="3" /><path d="M12 3v4m-4 5h.01M16 12h.01M9 16h6" /></>, chart: <><path d="M5 20V10m7 10V4m7 16v-7" /><path d="M3 20h18" /></>, check: <path d="m5 12 4 4L19 6" />, chevron: <path d="m6 9 6 6 6-6" />, facebook: <path d="M14 8h3V5h-3a4 4 0 0 0-4 4v2H7v3h3v5h3v-5h3l1-3h-4V9a1 1 0 0 1 1-1Z" />, globe: <><circle cx="12" cy="12" r="8" /><path d="M4 12h16M12 4c2 2.2 3 4.8 3 8s-1 5.8-3 8c-2-2.2-3-4.8-3-8s1-5.8 3-8Z" /></>, instagram: <><rect x="4" y="4" width="16" height="16" rx="5" /><circle cx="12" cy="12" r="3.5" /><path d="M17.5 6.5h.01" /></>, layers: <><path d="m12 4 8 4-8 4-8-4 8-4Z" /><path d="m4 12 8 4 8-4M4 16l8 4 8-4" /></>, mail: <><rect x="3" y="5" width="18" height="14" rx="2" /><path d="m4 7 8 6 8-6" /></>, message: <path d="M20 11.5a7.5 7.5 0 0 1-8 7.5 8 8 0 0 1-3-.6L4 20l1.7-4.5A7.3 7.3 0 0 1 4.5 11 7.5 7.5 0 0 1 12 4a7.5 7.5 0 0 1 8 7.5Z" />, monitor: <><rect x="3" y="4" width="18" height="13" rx="2" /><path d="M8 21h8m-4-4v4" /></>, send: <path d="m4 4 16 8-16 8 3-8-3-8Zm3 8h13" />, shield: <path d="M12 3 20 6v5c0 5-3.4 8.3-8 10-4.6-1.7-8-5-8-10V6l8-3Z" />, shop: <><path d="M4 10v10h16V10M3 10l2-6h14l2 6" /><path d="M3 10c0 2 3 3 4.5 0 1.5 3 4.5 3 6 0 1.5 3 4.5 2 7.5 0" /></>, sparkle: <path d="m12 3 1.6 5.4L19 10l-5.4 1.6L12 17l-1.6-5.4L5 10l5.4-1.6L12 3Zm6 12 .7 2.3L21 18l-2.3.7L18 21l-.7-2.3L15 18l2.3-.7L18 15Z" />, telegram: <path d="m21 4-3 16-6-5-3 3v-5L21 4ZM9 13l8-6" />, tiktok: <path d="M15 4v10.5a4.5 4.5 0 1 1-3-4.2V7c2.4 2.2 4.2 2.4 6 2V6c-1.8-.1-2.8-.8-3-2Z" />, users: <><circle cx="9" cy="9" r="3" /><path d="M3 20a6 6 0 0 1 12 0M16 7a3 3 0 0 1 0 6m1 1a5 5 0 0 1 4 6" /></>, website: <><circle cx="12" cy="12" r="8" /><path d="M4 12h16M12 4c1.4 2 2 4.7 2 8s-.6 6-2 8M7 7h10M7 17h10" /></>, workflow: <><rect x="4" y="4" width="6" height="6" rx="1" /><rect x="14" y="14" width="6" height="6" rx="1" /><path d="M10 7h3a3 3 0 0 1 3 3v4" /></>, zalo: <><rect x="4" y="4" width="16" height="16" rx="4" /><path d="M8 16 16 8M10 8h6v6" /></>,
};

function Icon({ name, className = "h-5 w-5" }: { name: IconName; className?: string }) { return <svg aria-hidden="true" className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{iconPaths[name]}</svg>; }
function FadeUp({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) { const reducedMotion = useReducedMotion(); return <motion.div className={className} initial={reducedMotion ? false : { opacity: 0, y: 24 }} whileInView={reducedMotion ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.15 }} transition={{ duration: reducedMotion ? 0 : 0.55, delay: reducedMotion ? 0 : delay, ease: "easeOut" }}>{children}</motion.div>; }

const channels: { name: string; icon: IconName; color: string; bg: string }[] = [
  { name: "Facebook", icon: "facebook", color: "text-blue-600", bg: "bg-blue-50" }, { name: "Instagram", icon: "instagram", color: "text-pink-500", bg: "bg-pink-50" }, { name: "Zalo", icon: "zalo", color: "text-sky-500", bg: "bg-sky-50" }, { name: "Telegram", icon: "telegram", color: "text-cyan-500", bg: "bg-cyan-50" }, { name: "Shopee", icon: "shop", color: "text-orange-500", bg: "bg-orange-50" }, { name: "Lazada", icon: "shop", color: "text-indigo-500", bg: "bg-indigo-50" }, { name: "TikTok Shop", icon: "tiktok", color: "text-slate-800", bg: "bg-slate-100" }, { name: "Email", icon: "mail", color: "text-rose-500", bg: "bg-rose-50" }, { name: "Website", icon: "website", color: "text-emerald-500", bg: "bg-emerald-50" },
];
const features: { icon: IconName; title: string; text: string }[] = [
  { icon: "message", title: "Quản lý tin nhắn tập trung", text: "Tập trung mọi cuộc trò chuyện trong một hộp thư duy nhất." }, { icon: "users", title: "Phân công nhân viên tự động", text: "Chia hội thoại thông minh để đội ngũ phục vụ nhanh hơn." }, { icon: "layers", title: "Gắn thẻ & Phân loại", text: "Nắm rõ nhu cầu và trạng thái của từng khách hàng." }, { icon: "bot", title: "Trợ lý AI thông minh", text: "AI hiểu ngữ cảnh và hỗ trợ trả lời tự nhiên 24/7." }, { icon: "chart", title: "Thống kê & Báo cáo", text: "Theo dõi hiệu suất bằng dữ liệu rõ ràng, trực quan." }, { icon: "workflow", title: "Kịch bản tự động", text: "Tự động hóa những tác vụ lặp lại trong quy trình bán hàng." }, { icon: "shop", title: "Tạo đơn hàng nhanh", text: "Chốt đơn ngay trong cuộc trò chuyện với khách hàng." }, { icon: "globe", title: "Tích hợp CRM", text: "Đồng bộ dữ liệu để chăm sóc khách hàng xuyên suốt." }, { icon: "monitor", title: "Quản lý nhiều trang", text: "Quản lý nhiều tài khoản và thương hiệu trong một nơi." },
];
const faqs = [
  { question: "Hchat có giới hạn số lượng fanpage không?", answer: "Gói dịch vụ được thiết kế linh hoạt theo số lượng kênh và quy mô đội ngũ của anh." }, { question: "Dữ liệu của tôi có an toàn không?", answer: "Dữ liệu được bảo vệ theo từng tài khoản, credential không gửi xuống giao diện và quyền truy cập được kiểm soát." }, { question: "Hchat hỗ trợ những kênh nào?", answer: "Hchat hỗ trợ Facebook, Instagram, Zalo, Telegram, sàn thương mại điện tử, Email và Website." }, { question: "Tôi có thể dùng thử trước khi đăng ký không?", answer: "Có. Anh có thể bắt đầu với gói miễn phí và nâng cấp khi đội ngũ sẵn sàng." },
];

function Brand() { return <a href="#top" className="flex items-center gap-2 text-slate-950" aria-label="Hchat - về đầu trang"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-600 text-white shadow-lg shadow-blue-600/20"><Icon name="message" className="h-5 w-5" /></span><span className="text-xl font-extrabold tracking-tight">Hchat</span></a>; }
function InboxMockup() {
  const conversations = [
    { name: "Quyền Hoàng", preview: "345", time: "14:05", color: "bg-amber-100", initial: "Q", tag: "Tư vấn", tagColor: "bg-red-500" },
    { name: "Nguyễn Ngọc Hữu", preview: "Dạ vâng ạ! Với mục tiêu tiếp, em xin giới thiệu...", time: "09:27", color: "bg-slate-700", initial: "N", tag: "Đã gửi", tagColor: "bg-emerald-500" },
  ];
  return <div className="overflow-hidden rounded-xl border border-slate-200 bg-white text-left shadow-2xl shadow-blue-900/10">
    <div className="flex h-10 items-center justify-between bg-blue-600 px-3 text-white sm:h-12 sm:px-4"><div className="flex items-center gap-1.5 text-[10px] font-bold sm:text-xs"><span className="flex h-5 w-5 items-center justify-center rounded-full border border-white/80 text-[9px]">☻</span>nhuu</div><nav className="hidden items-center gap-5 text-[9px] font-semibold sm:flex"><span className="font-bold">Hộp thư</span><span>Đơn hàng</span><span>Bài viết</span><span>Thống kê</span><span>Cài đặt</span></nav><div className="flex items-center gap-2 text-[8px] sm:gap-3 sm:text-[9px]"><span className="hidden text-right sm:block">nguyenhung2k4gh<br /><span className="text-[7px] opacity-70">ADMIN</span></span><span className="flex h-6 w-6 items-center justify-center rounded-full border border-white/60 text-[9px]">N</span><span>⌄</span></div></div>
    <div className="grid min-h-[300px] grid-cols-[24px_28%_1fr] sm:min-h-[390px] sm:grid-cols-[34px_29%_1fr_25%]">
      <aside className="flex flex-col items-center gap-3 bg-blue-600 pt-4 text-white"><span className="rounded border border-white/80 p-1"><Icon name="message" className="h-3 w-3" /></span><Icon name="mail" className="h-3 w-3 opacity-80" /></aside>
      <section className="min-w-0 border-r border-slate-200 bg-white"><div className="flex gap-1 border-b border-slate-100 p-2"><div className="flex min-w-0 flex-1 items-center rounded-md border border-slate-200 px-2 text-[8px] text-slate-400"><span className="mr-1">⌕</span>Tìm tên, sđt...</div><button type="button" className="hidden rounded-md border border-slate-200 px-2 text-[8px] text-slate-500 sm:block">Lọc theo</button><button type="button" className="rounded-md border border-slate-200 px-2 text-xs text-slate-500">+</button></div><div className="flex items-center justify-between border-b border-slate-100 px-2 py-2 text-[9px] font-bold text-slate-700 sm:px-3 sm:text-[10px]">Tất cả hội thoại <span className="ml-1 font-normal text-slate-400">2</span><span className="ml-auto text-slate-400">☷</span></div>{conversations.map((item, index) => <div key={item.name} className={`border-b border-slate-100 p-2 ${index === 0 ? "bg-blue-50" : ""}`}><div className="flex items-start gap-2"><span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full ${item.color} text-[10px] font-bold text-slate-700`}>{item.initial}{index === 1 && <i className="-ml-1 -mt-5 flex h-3 w-3 items-center justify-center rounded-full bg-red-500 text-[7px] not-italic text-white">5</i>}</span><div className="min-w-0 flex-1"><div className="flex justify-between gap-1"><p className="truncate text-[9px] font-bold text-slate-700">{item.name}</p><span className="text-[7px] text-slate-400">{item.time}</span></div><p className="truncate text-[8px] text-slate-500">{item.preview}</p><span className={`mt-1 inline-block rounded px-1.5 py-0.5 text-[7px] font-bold text-white ${item.tagColor}`}>{item.tag}</span><span className="float-right mt-1 text-[7px] text-sky-500">Zalo</span></div></div></div>)}</section>
      <section className="flex min-w-0 flex-col bg-slate-100/80"><div className="flex items-center gap-2 border-b border-slate-200 bg-white px-3 py-2 sm:px-4"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-amber-100 text-[10px] font-bold text-slate-700">Q</span><div><p className="text-[10px] font-bold text-slate-800 sm:text-xs">Quyền Hoàng</p><span className="text-[7px] text-sky-500">Zalo</span></div><div className="ml-auto flex items-center gap-1 text-[8px] text-slate-400">Bot tự động <span className="h-3 w-6 rounded-full bg-slate-300"><i className="ml-0.5 mt-0.5 block h-2 w-2 rounded-full bg-white" /></span></div></div><div className="m-2 rounded-lg border border-slate-200 bg-white px-3 py-2 shadow-sm sm:m-3"><p className="text-[8px] font-bold text-slate-700">⌖ &nbsp; Tin đã ghim · 1/10</p><p className="mt-1 text-[8px] text-slate-500">hi</p></div><div className="flex-1 space-y-4 px-3 py-2 sm:px-4"><div className="ml-auto flex w-fit items-end gap-1"><span className="rounded-xl bg-blue-100 px-3 py-2 text-[9px] text-slate-700">test</span><span className="text-[9px] text-emerald-500">✓</span></div><div className="ml-auto flex w-fit items-end gap-1"><span className="rounded-xl bg-blue-100 px-3 py-2 text-[9px] text-slate-700">123</span><span className="text-[9px] text-emerald-500">✓</span></div><div className="flex items-end gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-amber-100 text-[10px] font-bold">Q</span><span className="rounded-xl bg-white px-3 py-2 text-[9px] text-slate-700 shadow-sm">345</span></div></div><div className="border-t border-slate-200 bg-white p-2"><div className="grid grid-cols-5 gap-px text-center text-[7px] font-semibold text-white"><span className="bg-red-500 py-1">● Tư vấn</span><span className="bg-slate-400 py-1">Kiểm hàng</span><span className="bg-violet-500 py-1">Mua hàng</span><span className="bg-emerald-500 py-1">Đã gửi</span><span className="bg-sky-500 py-1">Hết hàng</span></div><div className="flex items-center justify-between py-2 text-[8px] text-slate-400"><span>✦ AI gợi ý</span><span>⟳</span></div><p className="truncate text-[8px] text-slate-400">Nhập tin nhắn... (gõ / để chèn mẫu trả lời nhanh, Shift+Enter để xuống dòng)</p><div className="mt-2 flex justify-end gap-2 text-slate-400"><span>?</span><span>⌕</span><span>▧</span><span className="rounded bg-blue-600 px-2 py-1 text-white">➤</span></div></div></section>
      <aside className="hidden border-l border-slate-200 bg-white sm:block"><div className="flex border-b border-slate-100 text-[9px] font-semibold text-slate-500"><span className="flex-1 px-3 py-3 text-center">Thông tin</span><span className="flex-1 border-b-2 border-blue-600 px-3 py-3 text-center text-blue-600">Tạo đơn</span></div><div className="m-3 rounded-lg border border-slate-200 bg-slate-50 p-3"><h3 className="text-[10px] font-bold text-slate-800">Tạo đơn</h3><p className="mt-2 text-[8px] leading-4 text-slate-500">Bắt đầu tạo đơn hàng từ hội thoại này.</p><button type="button" className="mt-3 w-full rounded-md bg-blue-600 py-2 text-[8px] font-bold text-white">+ Tạo đơn</button></div></aside>
    </div>
  </div>;
}
function ChannelCard({ channel }: { channel: typeof channels[number] }) { return <div className="flex flex-col items-center gap-3 rounded-xl border border-slate-100 bg-white px-3 py-4 shadow-sm transition hover:-translate-y-1 hover:border-blue-100 hover:shadow-md"><span className={`flex h-11 w-11 items-center justify-center rounded-xl ${channel.bg} ${channel.color}`}><Icon name={channel.icon} className="h-5 w-5" /></span><span className="text-xs font-semibold text-slate-600">{channel.name}</span></div>; }
function PricingCard({ name, price, description, featured, items }: { name: string; price: string; description: string; featured?: boolean; items: string[] }) { return <div className={`relative rounded-2xl border p-5 text-left transition hover:-translate-y-1 ${featured ? "border-blue-500 bg-white shadow-xl shadow-blue-100" : "border-slate-200 bg-white shadow-sm"}`}>{featured && <span className="absolute -top-3 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-full bg-blue-600 px-3 py-1 text-[11px] font-bold text-white">Phổ biến nhất</span>}<h3 className="text-base font-bold text-slate-900">{name}</h3><p className="mt-2 min-h-10 text-xs leading-5 text-slate-500">{description}</p><p className="mt-5 text-2xl font-extrabold text-slate-900">{price}<span className="text-xs font-medium text-slate-400">{price !== "0đ" && " / tháng"}</span></p><button type="button" className={`mt-5 w-full rounded-lg px-3 py-2.5 text-xs font-bold transition ${featured ? "bg-blue-600 text-white hover:bg-blue-700" : "border border-blue-200 bg-white text-blue-600 hover:bg-blue-50"}`}>Bắt đầu ngay</button><ul className="mt-5 space-y-3 text-xs text-slate-600">{items.map(item => <li key={item} className="flex gap-2"><Icon name="check" className="h-4 w-4 shrink-0 text-emerald-500" />{item}</li>)}</ul></div>; }

export function LandingPage({ user, onDashboard, onLogin, onRegister }: LandingPageProps) {
  const [openFaq, setOpenFaq] = React.useState<number | null>(0);
  const [mobileMenuOpen, setMobileMenuOpen] = React.useState(false);
  const landingLinks = [["Sản phẩm", "#tinh-nang"], ["Tích hợp", "#kenh-tich-hop"], ["Bảng giá", "#bang-gia"], ["Tài nguyên", "#faq"]] as const;
  return <div id="top" className="min-h-screen overflow-x-hidden bg-white font-sans text-slate-900">
    <header className="sticky top-0 z-40 border-b border-slate-100/80 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 lg:px-8"><Brand /><nav className="hidden items-center gap-9 text-sm font-medium text-slate-500 md:flex" aria-label="Điều hướng chính">{landingLinks.map(([label, href]) => <a key={href} className="transition hover:text-blue-600" href={href}>{label}</a>)}</nav><div className="flex items-center gap-2"><select aria-label="Chọn ngôn ngữ" className="hidden bg-transparent px-2 py-2 text-xs font-semibold text-slate-500 outline-none sm:block"><option>VN</option><option>EN</option></select><button type="button" aria-label={mobileMenuOpen ? "Đóng menu điều hướng" : "Mở menu điều hướng"} aria-controls="mobile-navigation" aria-expanded={mobileMenuOpen} onClick={() => setMobileMenuOpen(open => !open)} className="rounded-lg border border-slate-200 p-2 text-slate-600 md:hidden"><span className="sr-only">Menu</span><span className="block h-0.5 w-5 bg-current" /><span className="mt-1 block h-0.5 w-5 bg-current" /><span className="mt-1 block h-0.5 w-5 bg-current" /></button>{user ? <button type="button" onClick={onDashboard} aria-label={`Mở Dashboard cho ${user.email}`} className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700 transition hover:border-blue-300 hover:text-blue-700"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-blue-600 text-[10px] text-white">{user.email.charAt(0).toUpperCase()}</span><span className="hidden max-w-[140px] truncate sm:block">{user.email}</span></button> : <><button type="button" aria-label="Đăng nhập" onClick={onLogin} className="hidden px-3 py-2 text-xs font-semibold text-slate-600 hover:text-blue-600 sm:block">Đăng nhập</button><button type="button" aria-label="Đăng ký" onClick={onRegister} className="rounded-lg border border-blue-600 px-4 py-2 text-xs font-bold text-blue-600 transition hover:bg-blue-600 hover:text-white">Đăng ký miễn phí</button></>}</div></div>{mobileMenuOpen && <nav id="mobile-navigation" aria-label="Điều hướng trên thiết bị di động" className="border-t border-slate-100 px-5 py-3 md:hidden"><div className="mx-auto flex max-w-6xl flex-col gap-1">{landingLinks.map(([label, href]) => <a key={href} className="rounded-lg px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50 hover:text-blue-600" href={href} onClick={() => setMobileMenuOpen(false)}>{label}</a>)}</div></nav>}</header>
    <main>
      <section className="relative overflow-hidden bg-gradient-to-b from-[#edf5ff] via-[#f7fbff] to-white px-5 pb-12 pt-20 lg:px-8 lg:pb-16 lg:pt-24"><div className="pointer-events-none absolute left-1/2 top-0 h-96 w-[42rem] -translate-x-1/2 rounded-full bg-blue-100/40 blur-3xl" /><div className="relative mx-auto max-w-6xl"><FadeUp className="mx-auto max-w-4xl text-center"><span className="inline-flex items-center gap-2 rounded-full border border-blue-100 bg-white/80 px-4 py-2 text-xs font-medium text-blue-600 shadow-sm"><span className="h-1.5 w-1.5 rounded-full bg-blue-500" />Hchat AI 2.0 đã ra mắt <Icon name="arrow" className="h-3.5 w-3.5" /></span><h1 className="mx-auto mt-8 max-w-4xl text-4xl font-semibold leading-[1.08] tracking-[-0.045em] text-slate-950 sm:text-5xl lg:text-[4rem]">Quản lý tin nhắn đa kênh &amp; <span className="text-blue-600">AI<br className="hidden sm:block" /> Chatbot tự động</span></h1><p className="mx-auto mt-7 max-w-2xl text-base font-normal leading-7 text-slate-500 sm:text-lg">Hchat kết nối Facebook, Zalo, Instagram, WhatsApp và Website. Tự động hóa bán hàng với AI Chatbot thông minh, tăng x3 tỷ lệ chốt đơn.</p><div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row"><button type="button" onClick={onRegister} className="rounded-full bg-gradient-to-r from-blue-600 to-cyan-500 px-7 py-3.5 text-sm font-semibold text-white shadow-lg shadow-blue-200 transition hover:-translate-y-0.5 hover:shadow-xl">Bắt đầu dùng thử miễn phí</button><button type="button" className="inline-flex items-center rounded-full border border-slate-200 bg-white px-7 py-3.5 text-sm font-medium text-blue-600 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-200"><span className="mr-2 flex h-5 w-5 items-center justify-center rounded-full border border-blue-500 text-[10px]">▶</span>Xem demo thực tế</button></div><p className="mt-5 text-xs font-normal text-slate-400">Miễn phí 14 ngày • Không cần thẻ tín dụng • Setup trong 5 phút</p></FadeUp><FadeUp className="mx-auto mt-14 max-w-5xl" delay={0.12}><InboxMockup /></FadeUp></div></section>
      <FadeUp><section id="kenh-tich-hop" className="scroll-mt-24 border-b border-slate-100 px-5 py-14 lg:px-8"><div className="mx-auto max-w-5xl text-center"><h2 className="text-2xl font-black tracking-tight sm:text-3xl">Tích hợp tất cả kênh bán hàng của bạn</h2><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-slate-500">Kết nối liền mạch với những nơi khách hàng của bạn đang hiện diện.</p><div className="mx-auto mt-8 grid max-w-4xl grid-cols-3 gap-3 sm:grid-cols-5 lg:grid-cols-9">{channels.map(channel => <ChannelCard key={channel.name} channel={channel} />)}</div></div></section></FadeUp>
      <section id="tinh-nang" className="scroll-mt-24 px-5 py-20 lg:px-8"><div className="mx-auto max-w-6xl"><FadeUp className="text-center"><span className="text-xs font-bold uppercase tracking-[0.2em] text-blue-600">Mọi thứ trong tầm tay</span><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Tính năng cốt lõi cho tăng trưởng</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-6 text-slate-500">Tối ưu từng bước trong quy trình bán hàng và chăm sóc khách hàng.</p></FadeUp><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map((feature, index) => <FadeUp key={feature.title} delay={index * 0.04}><article className="h-full rounded-xl border border-slate-100 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-md"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-blue-50 text-blue-600"><Icon name={feature.icon} /></span><h3 className="mt-4 text-sm font-bold text-slate-800">{feature.title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{feature.text}</p></article></FadeUp>)}</div></div></section>
      <section className="bg-[#f7fbff] px-5 py-20 lg:px-8"><div className="mx-auto max-w-5xl"><FadeUp className="text-center"><span className="text-xs font-bold uppercase tracking-[0.2em] text-blue-600">Bắt đầu thật đơn giản</span><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Bắt đầu trong 3 bước đơn giản</h2></FadeUp><div className="relative mt-12 grid gap-10 md:grid-cols-3 md:gap-6"><div className="absolute left-[18%] right-[18%] top-6 hidden border-t border-dashed border-blue-200 md:block" />{["Đăng ký tài khoản", "Kết nối các kênh", "Tận hưởng kết quả"].map((title, index) => <FadeUp key={title} delay={index * 0.1} className="relative text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-full border-4 border-white bg-blue-600 text-lg font-black text-white shadow-lg shadow-blue-200">{index + 1}</span><h3 className="mt-5 text-sm font-bold">{title}</h3><p className="mx-auto mt-2 max-w-[13rem] text-xs leading-5 text-slate-500">{["Tạo tài khoản miễn phí chỉ trong vài phút.", "Kết nối Facebook, Zalo và các kênh bán hàng.", "Để Hchat đồng hành và giúp anh tăng trưởng."][index]}</p></FadeUp>)}</div></div></section>
      <section className="px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-2"><FadeUp><div className="relative mx-auto flex min-h-[22rem] w-full max-w-md items-center justify-center overflow-hidden rounded-3xl bg-[#f7fbff]"><div className="absolute h-64 w-64 rounded-full bg-blue-500 shadow-2xl shadow-blue-300"><div className="flex h-full items-center justify-center text-white"><Icon name="bot" className="h-24 w-24" /></div></div><span className="absolute right-6 top-8 rounded-full bg-white px-3 py-2 text-[11px] font-bold text-emerald-600 shadow-lg"><span className="mr-1 inline-block h-2 w-2 rounded-full bg-emerald-500" />Chatbot đang trả lời...</span><div className="absolute bottom-7 left-8 rounded-xl bg-white px-4 py-3 text-xs text-slate-600 shadow-xl">AI đang hỗ trợ khách hàng <Icon name="sparkle" className="ml-1 inline h-3 w-3 text-blue-600" /></div></div></FadeUp><FadeUp delay={0.1}><span className="text-xs font-bold uppercase tracking-[0.2em] text-blue-600">Trợ lý của đội ngũ</span><h2 className="mt-3 text-3xl font-black leading-tight tracking-tight sm:text-4xl">Chatbot AI - Nhân viên bán hàng không bao giờ ngủ</h2><p className="mt-5 text-sm leading-7 text-slate-500">Để AI hỗ trợ những công việc lặp lại, phản hồi khách hàng nhanh chóng và giúp nhân viên tập trung vào những cuộc trò chuyện quan trọng.</p><ul className="mt-6 space-y-4 text-sm text-slate-700">{["Tự động trả lời khách 24/7", "Gợi ý câu trả lời thông minh", "Phân tích cảm xúc khách hàng", "Hỗ trợ tạo đơn hàng tự động"].map(item => <li key={item} className="flex items-center gap-3"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-emerald-50 text-emerald-500"><Icon name="check" className="h-3 w-3" /></span>{item}</li>)}</ul><button type="button" onClick={onRegister} className="mt-8 rounded-lg bg-blue-600 px-5 py-3 text-sm font-bold text-white shadow-md shadow-blue-200 transition hover:bg-blue-700">Khám phá AI <Icon name="arrow" className="ml-2 inline h-4 w-4" /></button></FadeUp></div></section>
      <section id="bang-gia" className="scroll-mt-24 bg-[#f7fbff] px-5 py-20 lg:px-8"><div className="mx-auto max-w-6xl"><FadeUp className="text-center"><span className="text-xs font-bold uppercase tracking-[0.2em] text-blue-600">Đơn giản và minh bạch</span><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Gói giải pháp linh hoạt cho mọi nhu cầu</h2><div className="mx-auto mt-6 inline-flex rounded-full bg-white p-1 shadow-sm"><button type="button" className="rounded-full bg-blue-600 px-4 py-2 text-xs font-bold text-white">Hàng tháng</button><button type="button" className="rounded-full px-4 py-2 text-xs font-semibold text-slate-500">Hàng năm <span className="text-emerald-500">-20%</span></button></div></FadeUp><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[{ name: "Miễn phí", price: "0đ", description: "Bắt đầu khám phá Hchat", items: ["1 kênh kết nối", "100 tin nhắn/tháng", "Hỗ trợ cộng đồng"] }, { name: "Cơ bản", price: "199.000đ", description: "Cho cá nhân và cửa hàng nhỏ", items: ["3 kênh kết nối", "Không giới hạn tin nhắn", "Phân loại hội thoại"] }, { name: "Nâng cao", price: "399.000đ", description: "Cho đội ngũ đang phát triển", featured: true, items: ["10 kênh kết nối", "Trợ lý AI thông minh", "Phân công tự động"] }, { name: "Chuyên nghiệp", price: "1.099.000đ", description: "Cho doanh nghiệp lớn", items: ["Không giới hạn kênh", "AI theo kiến thức riêng", "Báo cáo nâng cao"] }].map(plan => <FadeUp key={plan.name}><PricingCard {...plan} /></FadeUp>)}</div></div></section>
      <section className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-6xl"><FadeUp className="text-center"><span className="text-xs font-bold uppercase tracking-[0.2em] text-blue-600">Khách hàng nói gì?</span><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Trải nghiệm được 10.000+ khách hàng tin dùng</h2></FadeUp><div className="mt-10 grid gap-4 md:grid-cols-3">{[{ name: "Nguyễn Minh Anh", role: "Chủ shop thời trang", text: "Hchat giúp đội ngũ không còn bỏ sót tin nhắn và xử lý đơn nhanh hơn rất nhiều." }, { name: "Trần Hoàng Nam", role: "Founder thương hiệu mỹ phẩm", text: "Giao diện dễ dùng, AI gợi ý đúng ngữ cảnh và nhân viên phối hợp hiệu quả hơn." }, { name: "Lê Thu Hà", role: "Quản lý bán hàng", text: "Từ khi dùng Hchat, tôi theo dõi được toàn bộ kênh chỉ trong một màn hình." }].map(review => <article key={review.name} className="rounded-xl border border-slate-100 bg-white p-5 text-left shadow-sm"><div className="flex gap-0.5 text-amber-400">{"★★★★★"}</div><p className="mt-4 text-sm leading-6 text-slate-600">“{review.text}”</p><div className="mt-5 flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-blue-100 text-xs font-bold text-blue-600">{review.name.charAt(0)}</span><div><p className="text-xs font-bold text-slate-800">{review.name}</p><p className="text-[11px] text-slate-400">{review.role}</p></div></div></article>)}</div><div className="mt-12 grid grid-cols-2 gap-6 border-t border-slate-100 pt-10 sm:grid-cols-4"><div><p className="text-3xl font-black text-blue-600">10.000+</p><p className="mt-1 text-xs text-slate-500">Khách hàng</p></div><div><p className="text-3xl font-black text-blue-600">50M+</p><p className="mt-1 text-xs text-slate-500">Tin nhắn</p></div><div><p className="text-3xl font-black text-blue-600">95%</p><p className="mt-1 text-xs text-slate-500">Tỷ lệ hài lòng</p></div><div><p className="text-3xl font-black text-blue-600">0s</p><p className="mt-1 text-xs text-slate-500">Độ trễ phản hồi</p></div></div></div></section>
      <section id="faq" className="scroll-mt-24 bg-[#f7fbff] px-5 py-20 lg:px-8"><div className="mx-auto max-w-3xl"><FadeUp className="text-center"><span className="text-xs font-bold uppercase tracking-[0.2em] text-blue-600">Giải đáp</span><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Câu hỏi thường gặp</h2></FadeUp><div className="mt-10 space-y-3">{faqs.map((faq, index) => <FadeUp key={faq.question} delay={index * 0.04}><div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><button type="button" className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left text-sm font-semibold text-slate-800" aria-expanded={openFaq === index} onClick={() => setOpenFaq(openFaq === index ? null : index)}><span>{faq.question}</span><Icon name="chevron" className={`h-5 w-5 shrink-0 text-slate-400 transition ${openFaq === index ? "rotate-180" : ""}`} /></button>{openFaq === index && <p className="px-5 pb-5 text-sm leading-6 text-slate-500">{faq.answer}</p>}</div></FadeUp>)}</div></div></section>
      <section className="px-5 py-20 lg:px-8"><FadeUp className="mx-auto max-w-5xl rounded-3xl bg-gradient-to-br from-blue-600 to-blue-500 px-6 py-14 text-center text-white shadow-xl shadow-blue-200 sm:px-12"><h2 className="text-3xl font-black tracking-tight sm:text-4xl">Sẵn sàng tăng doanh số với <span className="text-blue-100">Hchat?</span></h2><p className="mx-auto mt-4 max-w-xl text-sm leading-6 text-blue-100">Bắt đầu quản lý tin nhắn thông minh và chăm sóc khách hàng hiệu quả hơn ngay hôm nay.</p><button type="button" onClick={onRegister} className="mt-7 rounded-lg bg-white px-6 py-3 text-sm font-bold text-blue-700 shadow-md transition hover:bg-blue-50">Bắt đầu dùng thử miễn phí <Icon name="arrow" className="ml-2 inline h-4 w-4" /></button></FadeUp></section>
    </main>
    <footer className="border-t border-slate-100 px-5 py-12 lg:px-8"><div className="mx-auto grid max-w-6xl gap-10 sm:grid-cols-2 lg:grid-cols-5"><div className="lg:col-span-2"><Brand /><p className="mt-4 max-w-xs text-sm leading-6 text-slate-500">Nền tảng quản lý tin nhắn đa kênh và AI Chatbot cho doanh nghiệp hiện đại.</p></div><div><h3 className="text-xs font-bold text-slate-800">Sản phẩm</h3><div className="mt-4 space-y-3 text-xs text-slate-500"><a className="block hover:text-blue-600" href="#tinh-nang">Tính năng</a><a className="block hover:text-blue-600" href="#bang-gia">Bảng giá</a></div></div><div><h3 className="text-xs font-bold text-slate-800">Hỗ trợ</h3><div className="mt-4 space-y-3 text-xs text-slate-500"><a className="block hover:text-blue-600" href="#faq">Câu hỏi thường gặp</a><a className="block hover:text-blue-600" href="#top">Liên hệ</a></div></div><div><h3 className="text-xs font-bold text-slate-800">Chính sách</h3><div className="mt-4 space-y-3 text-xs text-slate-500"><a className="block hover:text-blue-600" href="#top">Bảo mật</a><a className="block hover:text-blue-600" href="#top">Điều khoản</a></div></div></div><div className="mx-auto mt-10 max-w-6xl border-t border-slate-100 pt-6 text-xs text-slate-400">© 2026 Hchat. All rights reserved.</div></footer>
  </div>;
}
