import * as React from "react";
import { motion, useReducedMotion } from "framer-motion";
import type { AuthRole } from "../../state/auth.store.js";
import { LandingHeader } from "./LandingHeader.js";
import { LandingFooter } from "./LandingFooter.js";

export interface LandingPageProps {
  user: { email: string; role: AuthRole } | null;
  onDashboard: () => void;
  onLogin: () => void;
  onRegister: () => void;
  onLogout: () => void;
}

type IconName = "arrow" | "bolt" | "bot" | "chart" | "check" | "chevron" | "facebook" | "globe" | "google" | "instagram" | "layers" | "mail" | "message" | "monitor" | "send" | "shield" | "shop" | "sparkle" | "telegram" | "tiktok" | "users" | "whatsapp" | "website" | "workflow" | "zalo";

const iconPaths: Record<IconName, React.ReactNode> = {
  arrow: <path d="M5 12h14m-6-6 6 6-6 6" />, bolt: <path d="m13 2-9 12h7l-1 8 9-12h-7l1-8Z" />, bot: <><rect x="5" y="7" width="14" height="12" rx="3" /><path d="M12 3v4m-4 5h.01M16 12h.01M9 16h6" /></>, chart: <><path d="M5 20V10m7 10V4m7 16v-7" /><path d="M3 20h18" /></>, check: <path d="m5 12 4 4L19 6" />, chevron: <path d="m6 9 6 6 6-6" />, facebook: <path d="M14 8h3V5h-3a4 4 0 0 0-4 4v2H7v3h3v5h3v-5h3l1-3h-4V9a1 1 0 0 1 1-1Z" />, globe: <><circle cx="12" cy="12" r="8" /><path d="M4 12h16M12 4c2 2.2 3 4.8 3 8s-1 5.8-3 8c-2-2.2-3-4.8-3-8s1-5.8 3-8Z" /></>, google: <path d="M21 12h-9v3h5.2a5 5 0 1 1-1.5-5.2l2.2-2.2A8 8 0 1 0 20 12h1Z" />, instagram: <><rect x="4" y="4" width="16" height="16" rx="5" /><circle cx="12" cy="12" r="3.5" /><path d="M17.5 6.5h.01" /></>, layers: <><path d="m12 4 8 4-8 4-8-4 8-4Z" /><path d="m4 12 8 4 8-4M4 16l8 4 8-4" /></>, mail: <><rect x="3" y="5" width="18" height="14" rx="2" /><path d="m4 7 8 6 8-6" /></>, message: <path d="M20 11.5a7.5 7.5 0 0 1-8 7.5 8 8 0 0 1-3-.6L4 20l1.7-4.5A7.3 7.3 0 0 1 4.5 11 7.5 7.5 0 0 1 12 4a7.5 7.5 0 0 1 8 7.5Z" />, monitor: <><rect x="3" y="4" width="18" height="13" rx="2" /><path d="M8 21h8m-4-4v4" /></>, send: <path d="m4 4 16 8-16 8 3-8-3-8Zm3 8h13" />, shield: <path d="M12 3 20 6v5c0 5-3.4 8.3-8 10-4.6-1.7-8-5-8-10V6l8-3Z" />, shop: <><path d="M4 10v10h16V10M3 10l2-6h14l2 6" /><path d="M3 10c0 2 3 3 4.5 0 1.5 3 4.5 3 6 0 1.5 3 4.5 2 7.5 0" /></>, sparkle: <path d="m12 3 1.6 5.4L19 10l-5.4 1.6L12 17l-1.6-5.4L5 10l5.4-1.6L12 3Zm6 12 .7 2.3L21 18l-2.3.7L18 21l-.7-2.3L15 18l2.3-.7L18 15Z" />, telegram: <path d="m21 4-3 16-6-5-3 3v-5L21 4ZM9 13l8-6" />, tiktok: <path d="M15 4v10.5a4.5 4.5 0 1 1-3-4.2V7c2.4 2.2 4.2 2.4 6 2V6c-1.8-.1-2.8-.8-3-2Z" />, users: <><circle cx="9" cy="9" r="3" /><path d="M3 20a6 6 0 0 1 12 0M16 7a3 3 0 0 1 0 6m1 1a5 5 0 0 1 4 6" /></>, whatsapp: <path d="M20 11.5a8 8 0 0 1-12.8 6.4L4 19l1.2-3.1A8 8 0 1 1 20 11.5Z" />, website: <><circle cx="12" cy="12" r="8" /><path d="M4 12h16M12 4c1.4 2 2 4.7 2 8s-.6 6-2 8M7 7h10M7 17h10" /></>, workflow: <><rect x="4" y="4" width="6" height="6" rx="1" /><rect x="14" y="14" width="6" height="6" rx="1" /><path d="M10 7h3a3 3 0 0 1 3 3v4" /></>, zalo: <><rect x="4" y="4" width="16" height="16" rx="4" /><path d="M8 16 16 8M10 8h6v6" /></>,
};

function Icon({ name, className = "h-5 w-5" }: { name: IconName; className?: string }) { return <svg aria-hidden="true" className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{iconPaths[name]}</svg>; }
function FadeUp({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) { const reducedMotion = useReducedMotion(); return <motion.div className={className} initial={reducedMotion ? false : { opacity: 0, y: 24 }} whileInView={reducedMotion ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.15 }} transition={{ duration: reducedMotion ? 0 : 0.55, delay: reducedMotion ? 0 : delay, ease: "easeOut" }}>{children}</motion.div>; }

const channels: { name: string; description: string; logoUrl: string }[] = [
  { name: "Facebook Messenger", description: "Chăm sóc khách hàng từ Fanpage", logoUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b8/2021_Facebook_icon.svg" },
  { name: "Zalo OA", description: "Tương tác với khách hàng trên Zalo", logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/91/Icon_of_Zalo.svg" },
  { name: "Zalo Personal", description: "Quản lý tin nhắn Zalo cá nhân", logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/91/Icon_of_Zalo.svg" },
  { name: "Instagram", description: "Trả lời DM và comment tự động", logoUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Instagram_logo_2016.svg" },
  { name: "WhatsApp", description: "Kết nối khách hàng quốc tế", logoUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6b/WhatsApp.svg" },
  { name: "Telegram", description: "Quản lý group và tin nhắn", logoUrl: "https://upload.wikimedia.org/wikipedia/commons/8/82/Telegram_logo.svg" },
  { name: "Website Webchat", description: "Livechat trực tiếp trên website", logoUrl: "/landing-icons/website-webchat.svg" },
  { name: "Google Business", description: "Tin nhắn từ Google Maps & Search", logoUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Google_%22G%22_logo.svg" },
];
const features: { icon: IconName; title: string; text: string }[] = [
  { icon: "message", title: "Quản lý tin nhắn tập trung", text: "Tập trung mọi cuộc trò chuyện trong một hộp thư duy nhất." }, { icon: "users", title: "Phân công nhân viên tự động", text: "Chia hội thoại thông minh để đội ngũ phục vụ nhanh hơn." }, { icon: "layers", title: "Gắn thẻ & Phân loại", text: "Nắm rõ nhu cầu và trạng thái của từng khách hàng." }, { icon: "bot", title: "Trợ lý AI thông minh", text: "AI hiểu ngữ cảnh và hỗ trợ trả lời tự nhiên 24/7." }, { icon: "chart", title: "Thống kê & Báo cáo", text: "Theo dõi hiệu suất bằng dữ liệu rõ ràng, trực quan." }, { icon: "workflow", title: "Kịch bản tự động", text: "Tự động hóa những tác vụ lặp lại trong quy trình bán hàng." }, { icon: "shop", title: "Tạo đơn hàng nhanh", text: "Chốt đơn ngay trong cuộc trò chuyện với khách hàng." }, { icon: "globe", title: "Tích hợp CRM", text: "Đồng bộ dữ liệu để chăm sóc khách hàng xuyên suốt." }, { icon: "monitor", title: "Quản lý nhiều trang", text: "Quản lý nhiều tài khoản và thương hiệu trong một nơi." },
];
const faqs = [
  { question: "NhuuChat có giới hạn số lượng fanpage không?", answer: "Gói dịch vụ được thiết kế linh hoạt theo số lượng kênh và quy mô đội ngũ của anh." }, { question: "Dữ liệu của tôi có an toàn không?", answer: "Dữ liệu được bảo vệ theo từng tài khoản, credential không gửi xuống giao diện và quyền truy cập được kiểm soát." }, { question: "NhuuChat hỗ trợ những kênh nào?", answer: "NhuuChat hỗ trợ Facebook, Instagram, Zalo, Telegram, sàn thương mại điện tử, Email và Website." }, { question: "Tôi có thể dùng thử trước khi đăng ký không?", answer: "Có. Anh có thể bắt đầu với gói miễn phí và nâng cấp khi đội ngũ sẵn sàng." },
];
export const LANDING_PAGE_LINKS = [["Sản phẩm", "#tinh-nang"], ["Tích hợp", "#kenh-tich-hop"], ["Bảng giá", "#bang-gia"], ["Tài nguyên", "#faq"]] as const;

function InboxMockup() {
  const conversations = [
    { name: "Mai Lan", preview: "Cho mình hỏi giá sản phẩm này?", time: "14:05", color: "bg-amber-100", initial: "M", tag: "Tư vấn", tagColor: "bg-red-500" },
    { name: "Trần Kiên", preview: "Dạ vâng ạ, để em xem thêm các mẫu khác...", time: "09:27", color: "bg-slate-700", initial: "T", tag: "Đã gửi", tagColor: "bg-emerald-500" },
  ];
  return <div className="relative mx-auto">
    <div className="overflow-hidden rounded-xl border border-slate-200 bg-white text-left shadow-2xl shadow-blue-900/10">
    <div className="flex h-10 items-center justify-between bg-blue-600 px-3 text-white sm:h-12 sm:px-4"><div className="flex items-center gap-1.5 text-[10px] font-semibold sm:text-xs"><img className="h-5 w-10 object-contain" src="/nhuu-logo.svg" alt="NhuuChat" /></div><nav className="hidden items-center gap-5 text-[9px] font-semibold sm:flex"><span className="font-semibold">Hộp thư</span><span>Đơn hàng</span><span>Bài viết</span><span>Thống kê</span><span>Cài đặt</span></nav><div className="flex items-center gap-2 text-[8px] sm:gap-3 sm:text-[9px]"><span className="hidden text-right sm:block">admin_demo_01<br /><span className="text-[7px] opacity-70">ADMIN</span></span><span className="flex h-6 w-6 items-center justify-center rounded-full border border-white/60 text-[9px]">A</span><span>⌄</span></div></div>
    <div className="grid min-h-[300px] grid-cols-[24px_28%_1fr] sm:min-h-[390px] sm:grid-cols-[34px_29%_1fr_25%]">
      <aside className="flex flex-col items-center gap-3 bg-blue-600 pt-4 text-white"><span className="rounded border border-white/80 p-1"><Icon name="message" className="h-3 w-3" /></span><Icon name="mail" className="h-3 w-3 opacity-80" /></aside>
      <section className="min-w-0 border-r border-slate-200 bg-white"><div className="flex gap-1 border-b border-slate-100 p-2"><div className="flex min-w-0 flex-1 items-center rounded-md border border-slate-200 px-2 text-[8px] text-slate-400"><span className="mr-1">⌕</span>Tìm tên, sđt...</div><button type="button" className="hidden rounded-md border border-slate-200 px-2 text-[8px] text-slate-500 sm:block cursor-pointer transition-opacity hover:opacity-80">Lọc theo</button><button type="button" className="rounded-md border border-slate-200 px-2 text-xs text-slate-500 cursor-pointer transition-opacity hover:opacity-80">+</button></div><div className="flex items-center justify-between border-b border-slate-100 px-2 py-2 text-[9px] font-semibold text-slate-700 sm:px-3 sm:text-[10px]">Tất cả hội thoại <span className="ml-1 font-normal text-slate-400">2</span><span className="ml-auto text-slate-400">☷</span></div>{conversations.map((item, index) => <div key={item.name} className={`border-b border-slate-100 p-2 ${index === 0 ? "bg-blue-50" : ""}`}><div className="flex items-start gap-2"><span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full ${item.color} text-[10px] font-semibold text-slate-700`}>{item.initial}{index === 1 && <i className="-ml-1 -mt-5 flex h-3 w-3 items-center justify-center rounded-full bg-red-500 text-[7px] not-italic text-white">5</i>}</span><div className="min-w-0 flex-1"><div className="flex justify-between gap-1"><p className="truncate text-[9px] font-semibold text-slate-700">{item.name}</p><span className="text-[7px] text-slate-400">{item.time}</span></div><p className="truncate text-[8px] text-slate-500">{item.preview}</p><span className={`mt-1 inline-block rounded px-1.5 py-0.5 text-[7px] font-semibold text-white ${item.tagColor}`}>{item.tag}</span><span className="float-right mt-1 text-[7px] text-sky-500">Zalo</span></div></div></div>)}</section>
      <section className="flex min-w-0 flex-col bg-slate-100/80"><div className="flex items-center gap-2 border-b border-slate-200 bg-white px-3 py-2 sm:px-4"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-amber-100 text-[10px] font-semibold text-slate-700">M</span><div><p className="text-[10px] font-semibold text-slate-800 sm:text-xs">Mai Lan</p><span className="text-[7px] text-sky-500">Zalo</span></div><div className="ml-auto flex items-center gap-1 text-[8px] text-slate-400">Bot tự động <span className="h-3 w-6 rounded-full bg-slate-300"><i className="ml-0.5 mt-0.5 block h-2 w-2 rounded-full bg-white" /></span></div></div><div className="m-2 rounded-lg border border-slate-200 bg-white px-3 py-2 shadow-sm sm:m-3"><p className="text-[8px] font-semibold text-slate-700">⌖ &nbsp; Tin đã ghim · 1/10</p><p className="mt-1 text-[8px] text-slate-500">Chào mừng bạn đến với shop! Vui lòng để lại lời nhắn.</p></div><div className="flex-1 space-y-4 px-3 py-2 sm:px-4"><div className="ml-auto flex w-fit items-end gap-1"><span className="rounded-xl bg-blue-100 px-3 py-2 text-[9px] text-slate-700">Dạ shop chào chị ạ!</span><span className="text-[9px] text-emerald-500">✓</span></div><div className="ml-auto flex w-fit items-end gap-1"><span className="rounded-xl bg-blue-100 px-3 py-2 text-[9px] text-slate-700">Chị đang quan tâm mẫu nào bên em ạ?</span><span className="text-[9px] text-emerald-500">✓</span></div><div className="flex items-end gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-amber-100 text-[10px] font-semibold">M</span><span className="rounded-xl bg-white px-3 py-2 text-[9px] text-slate-700 shadow-sm">Cho mình hỏi giá sản phẩm này?</span></div></div><div className="border-t border-slate-200 bg-white p-2"><div className="grid grid-cols-5 gap-px text-center text-[7px] font-semibold text-white"><span className="bg-red-500 py-1">● Tư vấn</span><span className="bg-slate-400 py-1">Kiểm hàng</span><span className="bg-violet-500 py-1">Mua hàng</span><span className="bg-emerald-500 py-1">Đã gửi</span><span className="bg-sky-500 py-1">Hết hàng</span></div><div className="flex items-center justify-between py-2 text-[8px] text-slate-400"><span>✦ AI gợi ý</span><span>⟳</span></div><p className="truncate text-[8px] text-slate-400">Nhập tin nhắn... (gõ / để chèn mẫu trả lời nhanh, Shift+Enter để xuống dòng)</p><div className="mt-2 flex justify-end gap-2 text-slate-400"><span>?</span><span>⌕</span><span>▧</span><span className="rounded bg-blue-600 px-2 py-1 text-white">➤</span></div></div></section>
      <aside className="hidden border-l border-slate-200 bg-white sm:block"><div className="flex border-b border-slate-100 text-[9px] font-semibold text-slate-500"><span className="flex-1 px-3 py-3 text-center">Thông tin</span><span className="flex-1 border-b-2 border-blue-600 px-3 py-3 text-center text-blue-600">Tạo đơn</span></div><div className="m-3 rounded-lg border border-slate-200 bg-slate-50 p-3"><h3 className="text-[10px] font-semibold text-slate-800">Tạo đơn</h3><p className="mt-2 text-[8px] leading-4 text-slate-500">Bắt đầu tạo đơn hàng từ hội thoại này.</p><button type="button" className="mt-3 w-full rounded-md bg-blue-600 py-2 text-[8px] font-semibold text-white cursor-pointer transition-opacity hover:opacity-80">+ Tạo đơn</button></div></aside>
    </div>
    </div>
    <motion.div data-testid="landing-badge-ai" className="pointer-events-none absolute -right-3 -top-5 z-10 flex items-center gap-1.5 rounded-full border border-emerald-200 bg-white px-3 py-2 text-[9px] font-semibold text-slate-600 shadow-lg sm:-right-8 sm:px-4 sm:text-[10px]" animate={{ y: [-8, 8, -8] }} transition={{ repeat: Infinity, duration: 4, ease: "easeInOut" }}>
      <Icon name="sparkle" className="h-4 w-4 shrink-0 text-emerald-500" />
      <span>AI Auto-Reply Active • Khách VIP 100%</span>
    </motion.div>
    <motion.div data-testid="landing-badge-performance" className="pointer-events-none absolute -bottom-5 -left-3 z-10 flex items-start gap-2 rounded-xl bg-white px-3 py-2.5 shadow-xl sm:-left-8 sm:px-4 sm:py-3" animate={{ y: [-8, 8, -8] }} transition={{ repeat: Infinity, duration: 4, delay: 1, ease: "easeInOut" }}>
      <Icon name="bolt" className="mt-0.5 h-5 w-5 shrink-0 text-orange-500" />
      <span className="text-left"><strong className="block text-[11px] font-semibold text-blue-600 sm:text-xs">Tăng 300% hiệu suất</strong><span className="mt-0.5 block text-[9px] text-slate-500 sm:text-[10px]">Tự động chốt đơn Zalo &amp; FB</span></span>
    </motion.div>
  </div>;
}
function ChannelCard({ channel }: { channel: typeof channels[number] }) { return <article className="flex h-full flex-col items-center rounded-3xl border border-gray-100 bg-white p-10 text-center shadow-sm transition-all hover:-translate-y-1 hover:shadow-md"><span className="flex h-16 w-16 items-center justify-center rounded-2xl border border-gray-100 bg-white shadow-sm"><img src={channel.logoUrl} alt={channel.name} className="h-10 w-10 object-contain" /></span><h3 className="mt-6 text-xl font-semibold text-slate-800">{channel.name}</h3><p className="mt-3 text-lg font-normal leading-8 text-slate-500">{channel.description}</p></article>; }
function PricingCard({ name, price, description, featured, items }: { name: string; price: string; description: string; featured?: boolean; items: string[] }) { return <div className={`relative rounded-2xl border p-7 text-left transition hover:-translate-y-1 ${featured ? "border-blue-500 bg-white shadow-xl shadow-blue-100" : "border-slate-200 bg-white shadow-sm"}`}>{featured && <span className="absolute -top-3 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-full bg-blue-600 px-3 py-1 text-[11px] font-semibold text-white">Phổ biến nhất</span>}<h3 className="text-lg font-semibold text-slate-900">{name}</h3><p className="mt-2 min-h-10 text-sm leading-6 text-slate-500">{description}</p><p className="mt-5 text-3xl font-semibold text-slate-900">{price}<span className="text-xs font-medium text-slate-400">{price !== "0đ" && " / tháng"}</span></p><button type="button" className={`mt-5 w-full rounded-lg px-4 py-3 text-base font-semibold transition ${featured ? "bg-blue-600 text-white hover:bg-blue-700" : "border border-blue-200 bg-white text-blue-600 hover:bg-blue-50"} cursor-pointer`}>Bắt đầu ngay</button><ul className="mt-5 space-y-3 text-xs text-slate-600">{items.map(item => <li key={item} className="flex gap-2"><Icon name="check" className="h-4 w-4 shrink-0 text-emerald-500" />{item}</li>)}</ul></div>; }

export function LandingPage({ user, onDashboard, onLogin, onRegister, onLogout }: LandingPageProps) {
  const [openFaq, setOpenFaq] = React.useState<number | null>(0);
  const [mobileMenuOpen, setMobileMenuOpen] = React.useState(false);
  const reducedMotion = useReducedMotion();
  return <div id="top" className="min-h-screen overflow-x-hidden bg-white font-sans text-slate-900">
    <LandingHeader user={user} landingLinks={LANDING_PAGE_LINKS} mobileMenuOpen={mobileMenuOpen} onMobileMenuToggle={() => setMobileMenuOpen(open => !open)} onDashboard={onDashboard} onLogin={onLogin} onRegister={onRegister} onLogout={onLogout} onMobileLinkClick={() => setMobileMenuOpen(false)} />
    <main>
      <section className="relative overflow-hidden bg-gradient-to-b from-[#edf5ff] via-[#f7fbff] to-white px-5 pb-16 pt-24 lg:px-8 lg:pb-16 lg:pt-24"><div className="pointer-events-none absolute left-1/2 top-0 h-96 w-[42rem] -translate-x-1/2 rounded-full bg-blue-100/40 blur-3xl" /><div className="relative mx-auto max-w-6xl"><FadeUp className="mx-auto max-w-4xl text-center"><span className="inline-flex items-center gap-2 rounded-full border border-blue-100 bg-white/80 px-4 py-2 text-xs font-medium text-blue-600 shadow-sm"><span className="h-1.5 w-1.5 rounded-full bg-blue-500" />NhuuChat AI 2.0 đã ra mắt <Icon name="arrow" className="h-3.5 w-3.5" /></span><h1 className="mx-auto mt-8 max-w-4xl text-5xl font-semibold leading-[1.08] tracking-[-0.045em] text-slate-950 sm:text-6xl md:text-7xl lg:text-[5rem]">Quản lý tin nhắn đa kênh &amp; <span className="bg-gradient-to-r from-blue-600 to-cyan-500 bg-clip-text text-transparent">AI<br className="hidden sm:block" /> Chatbot tự động</span></h1><p className="mx-auto mt-7 max-w-2xl text-lg font-normal leading-8 text-slate-500 sm:text-xl">NhuuChat kết nối Facebook, Zalo, Instagram, WhatsApp và Website. Tự động hóa bán hàng với AI Chatbot thông minh, tăng x3 tỷ lệ chốt đơn.</p><div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row"><button type="button" onClick={onRegister} className="rounded-full bg-gradient-to-r from-blue-600 to-cyan-500 px-8 py-4 text-lg font-semibold text-white shadow-lg shadow-blue-200 transition hover:-translate-y-0.5 hover:shadow-xl cursor-pointer">Bắt đầu dùng thử miễn phí</button><button type="button" className="inline-flex items-center rounded-full border border-slate-200 bg-white px-8 py-4 text-lg font-medium text-blue-600 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-200 cursor-pointer"><span className="mr-2 flex h-5 w-5 items-center justify-center rounded-full border border-blue-500 text-[10px]">▶</span>Xem demo thực tế</button></div><p className="mt-5 text-xs font-normal text-slate-400">Miễn phí 14 ngày • Không cần thẻ tín dụng • Setup trong 5 phút</p></FadeUp><FadeUp className="mx-auto mt-16 w-full max-w-6xl" delay={0.12}><InboxMockup /></FadeUp></div></section>
      <FadeUp><section id="kenh-tich-hop" className="scroll-mt-24 border-b border-slate-100 bg-slate-50 px-5 py-24 lg:px-8"><div className="mx-auto max-w-6xl text-center"><h2 className="text-4xl font-semibold tracking-tight text-slate-900 md:text-5xl">Tích hợp tất cả kênh bán hàng của bạn</h2><p className="mx-auto mt-4 max-w-2xl text-lg font-normal leading-8 text-slate-500">Không còn bỏ sót tin nhắn. NhuuChat gom tất cả hội thoại về một nền tảng duy nhất, giúp đội ngũ hỗ trợ nhanh hơn 300%.</p><div className="mx-auto mt-16 grid max-w-6xl gap-8 sm:grid-cols-2 lg:grid-cols-4">{channels.map(channel => <ChannelCard key={channel.name} channel={channel} />)}</div></div></section></FadeUp>
      <section id="tinh-nang" className="scroll-mt-24 px-5 py-24 lg:px-8"><div className="mx-auto max-w-6xl"><FadeUp className="text-center"><span className="text-xs font-semibold uppercase tracking-[0.2em] text-blue-600">Mọi thứ trong tầm tay</span><h2 className="mt-3 text-4xl font-semibold tracking-tight md:text-5xl">Tính năng cốt lõi cho tăng trưởng</h2><p className="mx-auto mt-4 max-w-xl text-base leading-7 text-slate-500">Tối ưu từng bước trong quy trình bán hàng và chăm sóc khách hàng.</p></FadeUp><div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">{features.map((feature, index) => <FadeUp key={feature.title} delay={index * 0.04}><article className="h-full rounded-xl border border-slate-100 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-md"><span className="flex h-16 w-16 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Icon name={feature.icon} className="h-8 w-8" /></span><h3 className="mt-5 text-lg font-semibold text-slate-800">{feature.title}</h3><p className="mt-2 text-base leading-7 text-slate-500">{feature.text}</p></article></FadeUp>)}</div></div></section>
      <section className="bg-[#f7fbff] px-5 py-24 lg:px-8"><div className="mx-auto max-w-5xl"><FadeUp className="text-center"><span className="text-xs font-semibold uppercase tracking-[0.2em] text-blue-600">Bắt đầu thật đơn giản</span><h2 className="mt-3 text-4xl font-semibold tracking-tight md:text-5xl">Bắt đầu trong 3 bước đơn giản</h2></FadeUp><div className="relative mt-12 grid gap-10 md:grid-cols-3 md:gap-6"><div className="absolute left-[18%] right-[18%] top-6 hidden border-t border-dashed border-blue-200 md:block" />{["Đăng ký tài khoản", "Kết nối các kênh", "Tận hưởng kết quả"].map((title, index) => <FadeUp key={title} delay={index * 0.1} className="relative text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-full border-4 border-white bg-blue-600 text-lg font-semibold text-white shadow-lg shadow-blue-200">{index + 1}</span><h3 className="mt-5 text-sm font-semibold">{title}</h3><p className="mx-auto mt-2 max-w-[16rem] text-sm leading-6 md:text-base md:leading-7 text-slate-500">{["Tạo tài khoản miễn phí chỉ trong vài phút.", "Kết nối Facebook, Zalo và các kênh bán hàng.", "Để NhuuChat đồng hành và giúp anh tăng trưởng."][index]}</p></FadeUp>)}</div></div></section>
      <section className="px-5 py-24 lg:px-8"><div className="mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-2"><FadeUp><div className="relative mx-auto flex h-[360px] w-full max-w-[400px] items-center justify-center sm:h-[400px]">
        <motion.div aria-hidden="true" className="absolute h-[min(320px,78vw)] w-[min(320px,78vw)] rounded-3xl border-2 border-dashed border-blue-200/60" initial={{ rotate: 45 }} animate={reducedMotion ? { rotate: 45 } : { rotate: 405 }} transition={{ duration: 20, repeat: Infinity, ease: "linear" }} />
        <motion.div className="absolute inset-0 m-auto flex h-[260px] w-[260px] items-center justify-center rounded-[2rem] bg-white shadow-xl shadow-blue-100/80" animate={reducedMotion ? undefined : { y: [-8, 8, -8] }} transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}>
          <div className="flex h-[200px] w-[200px] items-center justify-center rounded-full bg-[#0090FF] text-white shadow-lg shadow-blue-300/50"><Icon name="bot" className="h-16 w-16" /></div>
        </motion.div>
        <motion.div className="absolute right-0 top-5 z-10 flex items-center gap-2 rounded-full bg-white px-3 py-2.5 text-[11px] font-medium text-slate-700 shadow-lg sm:-right-12 sm:top-8 sm:px-4 sm:text-sm" animate={reducedMotion ? undefined : { y: [-4, 4, -4] }} transition={{ duration: 3.5, repeat: Infinity, ease: "easeInOut", delay: 1 }}>
          <span className="relative flex h-2.5 w-2.5 shrink-0"><span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-green-500 opacity-75" /><span className="relative inline-flex h-2.5 w-2.5 rounded-full bg-green-500" /></span>Đang trả lời 12 khách hàng...
        </motion.div>
        <motion.div className="absolute bottom-5 left-0 z-10 w-[220px] rounded-2xl bg-white p-4 shadow-2xl sm:-left-16 sm:bottom-8" animate={reducedMotion ? undefined : { y: [-6, 6, -6] }} transition={{ duration: 4.5, repeat: Infinity, ease: "easeInOut", delay: 2 }}>
          <p className="mb-2 text-sm leading-5 text-slate-600">Sản phẩm này có hỗ trợ trả góp không shop?</p><div className="flex items-center gap-1.5 text-[#0090FF]"><Icon name="check" className="h-3.5 w-3.5 shrink-0" /><span className="text-[10px] font-bold">ĐÃ TỰ ĐỘNG TRẢ LỜI</span></div>
        </motion.div>
      </div></FadeUp><FadeUp delay={0.1}><span className="text-xs font-semibold uppercase tracking-[0.2em] text-blue-600">Trợ lý của đội ngũ</span><h2 className="mt-3 text-4xl font-semibold leading-tight tracking-tight md:text-5xl">Chatbot AI - Nhân viên bán hàng không bao giờ ngủ</h2><p className="mt-5 text-lg leading-8 text-slate-500">Để AI hỗ trợ những công việc lặp lại, phản hồi khách hàng nhanh chóng và giúp nhân viên tập trung vào những cuộc trò chuyện quan trọng.</p><ul className="mt-6 space-y-4 text-sm text-slate-700">{["Tự động trả lời khách 24/7", "Gợi ý câu trả lời thông minh", "Phân tích cảm xúc khách hàng", "Hỗ trợ tạo đơn hàng tự động"].map(item => <li key={item} className="flex items-center gap-3"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-emerald-50 text-emerald-500"><Icon name="check" className="h-3 w-3" /></span>{item}</li>)}</ul><button type="button" onClick={onRegister} className="mt-8 rounded-lg bg-blue-600 px-8 py-4 text-lg font-semibold text-white shadow-md shadow-blue-200 transition hover:bg-blue-700 cursor-pointer">Khám phá AI <Icon name="arrow" className="ml-2 inline h-4 w-4" /></button></FadeUp></div></section>
      <section id="bang-gia" className="scroll-mt-24 bg-[#f7fbff] px-5 py-24 lg:px-8"><div className="mx-auto max-w-6xl"><FadeUp className="text-center"><span className="text-xs font-semibold uppercase tracking-[0.2em] text-blue-600">Đơn giản và minh bạch</span><h2 className="mt-3 text-4xl font-semibold tracking-tight md:text-5xl">Gói giải pháp linh hoạt cho mọi nhu cầu</h2><div className="mx-auto mt-6 inline-flex rounded-full bg-white p-1 shadow-sm"><button type="button" className="rounded-full bg-blue-600 px-4 py-2 text-xs font-semibold text-white cursor-pointer transition-opacity hover:opacity-80">Hàng tháng</button><button type="button" className="rounded-full px-4 py-2 text-xs font-semibold text-slate-500 cursor-pointer transition-opacity hover:opacity-80">Hàng năm <span className="text-emerald-500">-20%</span></button></div></FadeUp><div className="mt-16 grid gap-8 md:grid-cols-2 lg:grid-cols-4">{[{ name: "Miễn phí", price: "0đ", description: "Bắt đầu khám phá NhuuChat", items: ["1 kênh kết nối", "100 tin nhắn/tháng", "Hỗ trợ cộng đồng"] }, { name: "Cơ bản", price: "199.000đ", description: "Cho cá nhân và cửa hàng nhỏ", items: ["3 kênh kết nối", "Không giới hạn tin nhắn", "Phân loại hội thoại"] }, { name: "Nâng cao", price: "399.000đ", description: "Cho đội ngũ đang phát triển", featured: true, items: ["10 kênh kết nối", "Trợ lý AI thông minh", "Phân công tự động"] }, { name: "Chuyên nghiệp", price: "1.099.000đ", description: "Cho doanh nghiệp lớn", items: ["Không giới hạn kênh", "AI theo kiến thức riêng", "Báo cáo nâng cao"] }].map(plan => <FadeUp key={plan.name}><PricingCard {...plan} /></FadeUp>)}</div></div></section>
      <section className="px-5 py-24 lg:px-8"><div className="mx-auto max-w-6xl"><FadeUp className="text-center"><span className="text-xs font-semibold uppercase tracking-[0.2em] text-blue-600">Khách hàng nói gì?</span><h2 className="mt-3 text-4xl font-semibold tracking-tight md:text-5xl">Trải nghiệm được 10.000+ khách hàng tin dùng</h2></FadeUp><div className="mt-12 grid gap-8 md:grid-cols-3">{[{ name: "Nguyễn Minh Anh", role: "Chủ shop thời trang", text: "NhuuChat giúp đội ngũ không còn bỏ sót tin nhắn và xử lý đơn nhanh hơn rất nhiều." }, { name: "Trần Hoàng Nam", role: "Founder thương hiệu mỹ phẩm", text: "Giao diện dễ dùng, AI gợi ý đúng ngữ cảnh và nhân viên phối hợp hiệu quả hơn." }, { name: "Lê Thu Hà", role: "Quản lý bán hàng", text: "Từ khi dùng NhuuChat, tôi theo dõi được toàn bộ kênh chỉ trong một màn hình." }].map(review => <article key={review.name} className="rounded-xl border border-slate-100 bg-white p-5 text-left shadow-sm"><div className="flex gap-0.5 text-amber-400">{"★★★★★"}</div><p className="mt-4 text-sm leading-6 text-slate-600">“{review.text}”</p><div className="mt-5 flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-blue-100 text-xs font-semibold text-blue-600">{review.name.charAt(0)}</span><div><p className="text-xs font-semibold text-slate-800">{review.name}</p><p className="text-[11px] text-slate-400">{review.role}</p></div></div></article>)}</div><div className="mt-12 grid grid-cols-2 gap-6 border-t border-slate-100 pt-10 sm:grid-cols-4"><div><p className="text-3xl font-semibold text-blue-600">10.000+</p><p className="mt-1 text-xs text-slate-500">Khách hàng</p></div><div><p className="text-3xl font-semibold text-blue-600">50M+</p><p className="mt-1 text-xs text-slate-500">Tin nhắn</p></div><div><p className="text-3xl font-semibold text-blue-600">95%</p><p className="mt-1 text-xs text-slate-500">Tỷ lệ hài lòng</p></div><div><p className="text-3xl font-semibold text-blue-600">0s</p><p className="mt-1 text-xs text-slate-500">Độ trễ phản hồi</p></div></div></div></section>
      <section id="faq" className="scroll-mt-24 bg-[#f7fbff] px-5 py-24 lg:px-8"><div className="mx-auto max-w-3xl"><FadeUp className="text-center"><span className="text-xs font-semibold uppercase tracking-[0.2em] text-blue-600">Giải đáp</span><h2 className="mt-3 text-4xl font-semibold tracking-tight md:text-5xl">Câu hỏi thường gặp</h2></FadeUp><div className="mt-10 space-y-3">{faqs.map((faq, index) => <FadeUp key={faq.question} delay={index * 0.04}><div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><button type="button" className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left text-sm font-semibold text-slate-800 cursor-pointer transition-opacity hover:opacity-80" aria-expanded={openFaq === index} onClick={() => setOpenFaq(openFaq === index ? null : index)}><span>{faq.question}</span><Icon name="chevron" className={`h-5 w-5 shrink-0 text-slate-400 transition ${openFaq === index ? "rotate-180" : ""}`} /></button>{openFaq === index && <p className="px-5 pb-5 text-base leading-7 text-slate-500">{faq.answer}</p>}</div></FadeUp>)}</div></div></section>
      <section className="px-5 py-24 lg:px-8"><FadeUp className="mx-auto max-w-5xl rounded-3xl bg-gradient-to-br from-blue-600 to-blue-500 px-6 py-14 text-center text-white shadow-xl shadow-blue-200 sm:px-12"><h2 className="text-4xl font-semibold tracking-tight md:text-5xl">Sẵn sàng tăng doanh số với <span className="text-blue-100">NhuuChat?</span></h2><p className="mx-auto mt-4 max-w-2xl text-base leading-7 text-blue-100">Bắt đầu quản lý tin nhắn thông minh và chăm sóc khách hàng hiệu quả hơn ngay hôm nay.</p><button type="button" onClick={onRegister} className="mt-7 rounded-lg bg-white px-8 py-4 text-lg font-semibold text-blue-700 shadow-md transition hover:bg-blue-50 cursor-pointer">Bắt đầu dùng thử miễn phí <Icon name="arrow" className="ml-2 inline h-4 w-4" /></button></FadeUp></section>
    </main>
    <LandingFooter />
  </div>;
}
