import * as React from "react";
import { useCallback, useEffect, useState } from "react";

import { apiRequest } from "../lib/api.js";
import { ConnectModal } from "../components/dashboard/ConnectModal.js";
import { DashboardTopbar, type DashboardAccount } from "../components/dashboard/DashboardTopbar.js";
import { PlatformIcon } from "../components/dashboard/PlatformIcon.js";

interface TelegramStatus { connected: boolean; displayName: string | null; username: string | null; }

export function DashboardPage({ token, refresh, onOpenInbox, onLogoClick, onNavigate, user, onLogout, onProfile }: { token: string; refresh?: () => Promise<string | null>; onOpenInbox: () => void; onLogoClick?: () => void; onNavigate?: (item: "Hội thoại" | "Đơn hàng" | "Bài viết" | "Thống kê" | "Cài đặt") => void; user?: DashboardAccount | null; onLogout?: () => void; onProfile?: () => void }) {
  const [status, setStatus] = useState<TelegramStatus | null>(null);
  const [showConnect, setShowConnect] = useState(false);
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState<"all" | "zalo" | "telegram">("all");
  const loadStatus = useCallback(() => apiRequest<TelegramStatus>("", "/api/v1/channels/telegram-personal/status", token, {}, refresh).then(setStatus).catch(() => setStatus({ connected: false, displayName: null, username: null })), [refresh, token]);
  useEffect(() => { void loadStatus(); }, [loadStatus]);
  const connected = status?.connected === true;
  const showTelegram = filter !== "zalo" && (!search || `${status?.displayName ?? "Telegram"} ${status?.username ?? ""}`.toLowerCase().includes(search.toLowerCase()));
  const accountCount = connected ? 1 : 0;
  const openModal = () => setShowConnect(true);

  return <main className="min-h-screen bg-[#f2f5f9] pt-16 text-[#273348] max-[700px]:px-[34px] max-[700px]:pt-28" aria-labelledby="dashboard-title">
     <DashboardTopbar onLogoClick={onLogoClick} onNavigate={onNavigate} user={user} onLogout={onLogout} onProfile={onProfile} />
    <div className="mx-auto w-full max-w-[954px]">
      <header className="mb-2 flex items-end justify-between gap-6 rounded-[14px] bg-white px-[17px] pb-4 pt-[19px] max-[700px]:items-stretch max-[700px]:flex-col">
        <div><h1 id="dashboard-title" className="mb-[18px] text-[21px] tracking-[-.02em]">Bảng điều khiển</h1><label className="flex w-[430px] max-w-[48vw] items-center gap-[9px] rounded-[9px] border border-[#e0e6ee] bg-white px-[14px] py-[11px] text-[#a3afbf] shadow-[0_1px_2px_rgba(42,55,74,.03)] max-[700px]:w-auto max-[700px]:max-w-none"><span className="text-[25px] leading-[15px]" aria-hidden="true">⌕</span><input className="w-full bg-transparent text-[13px] text-[#354258] outline-none placeholder:text-[#a0abbb]" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Tìm kiếm..." aria-label="Tìm kiếm tài khoản" /></label></div>
        <div className="flex items-center gap-[9px] max-[700px]:justify-end"><button className="h-10 w-10 rounded-[9px] border border-[#e0e6ee] bg-white text-[21px] text-[#69778b] focus-visible:outline-2 focus-visible:outline-[#86b8ff] focus-visible:outline-offset-2" type="button" aria-label="Làm mới" onClick={() => void loadStatus()}>↻</button><button className="h-10 rounded-[9px] border border-[#e0e6ee] bg-[#e9edf3] px-4 text-[13px] font-bold text-[#354258] focus-visible:outline-2 focus-visible:outline-[#86b8ff] focus-visible:outline-offset-2 max-[700px]:flex-1" type="button" onClick={openModal}><span className="text-lg">＋</span> Kết nối</button><button className="h-10 rounded-[9px] border border-[#e0e6ee] bg-white px-4 text-[13px] font-bold text-[#354258] opacity-72 focus-visible:outline-2 focus-visible:outline-[#86b8ff] focus-visible:outline-offset-2 max-[700px]:flex-1" type="button" disabled><span className="text-lg">♣</span> Gộp trang</button></div>
      </header>
      <nav className="mb-2 flex items-center gap-1 overflow-auto rounded-[12px] border border-[#e7ebf1] bg-white px-[14px] py-[9px]" aria-label="Lọc nền tảng"><button className={`flex items-center rounded-lg border-0 px-[13px] py-2 text-[13px] text-[#748196] focus-visible:outline-2 focus-visible:outline-[#86b8ff] focus-visible:outline-offset-2 ${filter === "all" ? "bg-[#dff2fc] font-bold text-[#187ba9]" : "bg-transparent"}`} type="button" onClick={() => setFilter("all")}><span className="mr-1 inline-grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-[#edf1f5]"><PlatformIcon provider="all" /></span> Tất cả <b className={`ml-[5px] inline-grid h-[21px] min-w-[21px] place-items-center rounded-full text-[11px] ${filter === "all" ? "bg-[#159fe0] text-white" : "bg-[#e7edf4] text-[#7f8b9b]"}`}>{accountCount}</b></button><button className={`flex items-center rounded-lg border-0 px-[13px] py-2 text-[13px] text-[#748196] focus-visible:outline-2 focus-visible:outline-[#86b8ff] focus-visible:outline-offset-2 ${filter === "zalo" ? "bg-[#dff2fc] font-bold text-[#187ba9]" : "bg-transparent"}`} type="button" onClick={() => setFilter("zalo")}><span className="mr-1 inline-grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-[#edf1f5]"><PlatformIcon provider="zalo" /></span> Zalo <b className={`ml-[5px] inline-grid h-[21px] min-w-[21px] place-items-center rounded-full text-[11px] ${filter === "zalo" ? "bg-[#159fe0] text-white" : "bg-[#e7edf4] text-[#7f8b9b]"}`}>0</b></button><button className={`flex items-center rounded-lg border-0 px-[13px] py-2 text-[13px] text-[#748196] focus-visible:outline-2 focus-visible:outline-[#86b8ff] focus-visible:outline-offset-2 ${filter === "telegram" ? "bg-[#dff2fc] font-bold text-[#187ba9]" : "bg-transparent"}`} type="button" onClick={() => setFilter("telegram")}><span className="mr-1 inline-grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-[#edf1f5]"><PlatformIcon provider="telegram" /></span> Telegram <b className={`ml-[5px] inline-grid h-[21px] min-w-[21px] place-items-center rounded-full text-[11px] ${filter === "telegram" ? "bg-[#159fe0] text-white" : "bg-[#e7edf4] text-[#7f8b9b]"}`}>{accountCount}</b></button></nav>
      <section className="min-h-[330px] rounded-[14px] border border-[#e8edf3] bg-white p-5" aria-labelledby="accounts-title"><div className="mb-[15px] flex items-center justify-between px-1"><h2 id="accounts-title" className="text-[14px]">Tài khoản đã kết nối</h2><span className="text-[12px] text-[#94a0af]">{accountCount} tài khoản</span></div>{!status ? <div className="py-20 text-center text-[13px] text-[#8591a1]">Đang kiểm tra kết nối...</div> : showTelegram && connected ? <button className="flex w-[395px] max-w-full cursor-pointer items-center rounded-[13px] border border-[#e3e8ef] bg-white px-[14px] py-[13px] text-left shadow-[0_2px_8px_rgba(37,55,78,.04)] hover:border-[#b9ddec] hover:shadow-[0_5px_14px_rgba(37,55,78,.08)] focus-visible:outline-2 focus-visible:outline-[#86b8ff] focus-visible:outline-offset-2" type="button" onClick={onOpenInbox}><span className="mr-[13px] grid h-[55px] w-[55px] shrink-0 place-items-center rounded-[9px] bg-gradient-to-br from-[#26394f] to-[#111923] text-[21px] font-bold text-white">{status.displayName?.slice(0, 1).toUpperCase() ?? "T"}</span><span className="grid min-w-0 gap-[7px]"><strong className="text-[14px]">{status.displayName ?? "Telegram cá nhân"}</strong><small className="flex items-center text-[12px] text-[#7e8b9c]"><span className="mr-[3px] inline-grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-[#edf1f5]"><PlatformIcon provider="telegram" /></span> {status.username ? `@${status.username}` : "Telegram cá nhân"}</small></span><span className="ml-auto text-[19px] text-[#f3a51d]" title="Đang hoạt động">●</span></button> : <div className="grid justify-items-center px-5 pb-20 pt-[100px] text-center"><div className="mb-[18px] grid h-[58px] w-[58px] place-items-center rounded-full bg-[#e9f6fc] text-[30px] text-[#22a8df]">＋</div><h3 className="mb-2 text-base">Chưa có tài khoản kết nối</h3><p className="text-[13px] text-[#8390a1]">Kết nối Telegram để bắt đầu nhận và trả lời tin nhắn.</p><button className="mt-5 cursor-pointer rounded-lg border-0 bg-[#2aa9e7] px-4 py-[10px] text-[12px] font-bold text-white focus-visible:outline-2 focus-visible:outline-[#86b8ff] focus-visible:outline-offset-2" type="button" onClick={openModal}>Kết nối tài khoản</button></div>}</section>
    </div>
    {showConnect && <ConnectModal token={token} refresh={refresh} onClose={() => setShowConnect(false)} onConnected={() => { void loadStatus(); }} />}
  </main>;
}
